name: Call API every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: curl -X GET https://tvu-bot-service.onrender.com
